### ISSUE TITLE
AWT listener in Toolkit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BrunoEberhard/minimal-j#2]
```
There is still a FocusListener of AWT used in the Toolkit / TextField.

```

Original issue reported on code.google.com by `bruno.eb...@pop.ch` on 29 Oct 2013 at 7:23

**Comment by BrunoEberhard** [comment]
No awt / swing imports anymore in Frontend class (former ClientToolkit). Focus handling should not be a part of application development anymore.
