### ISSUE TITLE
TableClickListener

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BrunoEberhard/minimal-j#4]
```
The above listener consists of a single action method with two parameters. what 
is the meaning of the second parameter selectedIds. Of course these should be 
the ids of all selected rows but in the current implementation (Swing and 
Lanterna) only a single row can be selected so this list will never contain 
more than one id.


```

Original issue reported on code.google.com by `Marco.Mu...@gmail.com` on 14 Nov 2013 at 10:02

**Comment by BrunoEberhard** [comment]
The interface is now call TableActionListener. There is still a method with a single object and a list of objects. The meaning is: the single object has the focus, the list contains all selected rows.

But the method is not of great use at the moment as tables in Swing and Web Frontend don't support multi selection.

**Comment by BrunoEberhard** [comment]
Swing and html UI now support multi selection. TablePage can be configured to allow multi selection.
