### ISSUE TITLE
FlowField

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BrunoEberhard/minimal-j#5]
```
Two issues regarding this class :

1. Naming : FlowField is a layout container so i prefer to call it FlowLayout 
instead of FlowField
2. What about the method addGap() ? Does this method do anything at all ?

```

Original issue reported on code.google.com by `Marco.Mu...@gmail.com` on 14 Nov 2013 at 1:36

**Comment by BrunoEberhard** [comment]
The functionality of FlowField is now in ObjectFormElement. A ObjectFormElement should represent an object by render it when show(T) is called. addGap() doesn't exists anymore. It added an empty line. This is now done with a formated string
