### ISSUE TITLE
PropertyFile encoding

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BrunoEberhard/minimal-j#7]
```
the property file in minimal-j example is not encoded using utf-8
```

Original issue reported on code.google.com by `Marco.Mu...@gmail.com` on 20 Nov 2013 at 10:29

**Comment by BrunoEberhard** [comment]
Yes, the properites are not UTF-8 but ISO-8859-1 . Not my idea but JDKs. See for example https://docs.oracle.com/javase/7/docs/api/java/util/PropertyResourceBundle.html

Not sure if I should change it to UTF-8. Added a new Control in Resources for this idea.

**Comment by BrunoEberhard** [comment]
In Java 9 the problem will be solved: http://openjdk.java.net/jeps/226

Till then minimal-j property files are ISO-8859-1.
