### ISSUE TITLE
Dependencies on java.awt and javax.swing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BrunoEberhard/minimal-j#8]
```
in project minimal-j which should be in fact independent from any client 
toolkit are still dependencies to java.awt and javax.swing classes as well.
look at ResourceHelper.java or  MnemonicText.java 
```

Original issue reported on code.google.com by `Marco.Mu...@gmail.com` on 21 Nov 2013 at 2:30

**Comment by BrunoEberhard** [comment]
The toolkits are now called frontends. And only the swing frontend contains any references to java.awt or javax.swing. The ResourceHelper is now called Resources. There are still two method to retrieve a javax.swing.Icon . But nobody is forced to use this methods.
